openapi: 3.0.3
info:
  title: AppsFlyer Aggregate Pull API V5 - Partners Daily Report
  version: "1.0.0"
  description: |
    Partners Daily Report (LTV aggregated metrics).
    Data is grouped by date, media_source, and campaign.
    Supports both UA (user acquisition) and retargeting.
    Data type: LTV.

servers:
  - url: https://hq1.appsflyer.com

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /api/agg-data/export/app/{app-id}/partners_by_date_report/v5:
    get:
      operationId: getPartnersDailyV5
      summary: Partners daily aggregated LTV report
      description: |
        Returns daily aggregated performance metrics by:
        - date
        - media_source
        - campaign

        Supports UA campaigns and retargeting campaigns via `reattr=true`.

        Data type: LTV.
      security:
        - BearerAuth: []
      parameters:
        # PATH
        - name: app-id
          in: path
          required: true
          description: Application ID.
          schema:
            type: string

        # REQUIRED QUERY PARAMETERS
        - name: from
          in: query
          required: true
          description: From date (report start date)
          schema:
            type: string
            format: date
            example: "2025-11-01"

        - name: to
          in: query
          required: true
          description: To date (report end date)
          schema:
            type: string
            format: date
            example: "2025-11-10"

        # OPTIONAL FILTERS
        - name: media_source
          in: query
          required: false
          description: |
            Filter by specific media source.
            Must be used together with category.

            Examples:
              media_source=facebook&category=facebook
              media_source=abc_example&category=standard
          schema:
            type: string

        - name: category
          in: query
          required: false
          description: |
            Controls how groupings behave.

            Definitions:
              - **standard** (default): get data for given media_source without extended breakdowns.
              - **facebook**: get Facebook data with extended groupings:
                    campaign_id, adset, adset_id, adgroup, adgroup_id.
              - **organic**: only organic data, no extended groupings.
              - **media_source** with no value or media_source=all: return all media sources without extended groupings.

          schema:
            type: string
            enum:
              - standard
              - facebook
              - organic
            example: standard

        - name: attribution_touch_type
          in: query
          required: false
          description: |
            Use to fetch view-through attribution (VTA) metrics.
            Example: attribution_touch_type=impression
          schema:
            type: string
            enum:
              - impression
            example: impression

        - name: currency
          in: query
          required: false
          description: |
            Currency of revenue and cost fields.

            - preferred → app-specific currency (default)
            - USD
          schema:
            type: string
            enum:
              - preferred
              - USD
            example: preferred

        - name: reattr
          in: query
          required: false
          description: |
            Switch between UA and Retargeting data.

            - "" (default): return UA data.
            - "true": return retargeting conversions data.

          schema:
            type: string
            enum:
              - "true"
              - ""
            example: "true"

        - name: timezone
          in: query
          required: false
          description: |
            Time zone of returned data.
            - If not set → UTC.
            - Must match the timezone configured in the app settings.

            Example:
              timezone=Europe/Paris

            Note:
            Timezone applies only to data after timezone was configured. Earlier data uses UTC.
          schema:
            type: string
            example: Europe/Paris

      responses:
        "200":
          description: CSV report returned successfully.
          content:
            text/csv:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request — invalid date range, limit, or parameters.
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: Unauthorized — token invalid or account suspended.
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: App ID not found or token mismatch.
          content:
            text/plain:
              schema:
                type: string
