openapi: 3.0.3
info:
  title: AppsFlyer Raw Data Pull API - Installs report (v5)
  version: "1.0.0"
  description: |
    Installs raw data export (non-organic).
    Records non-organic installs. The record is generated when a user opens the app for the first time.
    Data freshness: Real-time.

servers:
  - url: https://hq1.appsflyer.com

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /api/raw-data/export/app/{app-id}/installs_report/v5:
    get:
      operationId: getInstallsReportV5
      summary: Installs raw data report (non-organic)
      description: |
        Exports a raw-data report of non-organic installs.
        A record is generated when a user opens the app for the first time.
        Data freshness is real-time.
      security:
        - BearerAuth: []
      parameters:
        # Path parameter
        - name: app-id
          in: path
          required: true
          description: Application ID.
          schema:
            type: string

        # Required query parameters
        - name: from
          in: query
          required: true
          description: From date (report start date), inclusive.
          schema:
            type: string
            format: date
            example: "2025-11-01"

        - name: to
          in: query
          required: true
          description: To date (report end date), inclusive.
          schema:
            type: string
            format: date
            example: "2025-11-07"

        # Optional filters
        - name: media_source
          in: query
          required: false
          description: |
            Use to filter by a specific media source.

            Set both the category and media_source parameters as follows:
            - Facebook: category=facebook, media_source=facebook
            - Twitter: category=twitter, media_source=twitter
            - Others: category=standard, media_source={media source name}

            Examples:
            - media_source=facebook&category=facebook
            - media_source=abc_example&category=standard
          schema:
            type: string
            example: facebook

        - name: category
          in: query
          required: false
          description: |
            media_source category. Must be used together with media_source.

            Values:
            - standard
            - facebook
            - twitter
          schema:
            type: string
            enum:
              - standard
              - facebook
              - twitter
            example: standard

        - name: currency
          in: query
          required: false
          description: |
            Currency of revenue and cost.

            - preferred: app-specific currency (default)
            - USD
          schema:
            type: string
            enum:
              - preferred
              - USD
            example: preferred

        - name: timezone
          in: query
          required: false
          description: |
            Time zone used for the report.

            - If not sent, data returns using UTC.
            - To use the app-specific time zone, send the value configured in the app settings.
              For example: timezone=Europe/Paris

            Pulling data in the selected time zone is only available from the date
            when the timezone setting was made. Any prior data uses UTC.
          schema:
            type: string
            example: Europe/Paris

        - name: geo
          in: query
          required: false
          description: |
            Filter the data by country code.
            Limitation: only one country code per API call.
            Two-letter ISO 3166-1 alpha-2 country code (US, JP, GB…)
          schema:
            type: string
            maxLength: 2
            example: US

        - name: maximum_rows
          in: query
          required: false
          description: |
            Maximum number of rows returned by a single API call.

            Defaults:
            - If not sent: up to 200,000 rows.
            - 200000: Up to 200K rows returned.
            - 1000000: Up to 1M rows returned.
          schema:
            type: integer
            enum:
              - 200000
              - 1000000
            example: 200000

        - name: from_install_time
          in: query
          required: false
          description: From install time (start of install time-based filter).
          schema:
            type: string
            format: date-time
            example: "2025-11-01T00:00:00Z"

        - name: to_install_time
          in: query
          required: false
          description: To install time (end of install time-based filter).
          schema:
            type: string
            format: date-time
            example: "2025-11-07T23:59:59Z"

        - name: agency
          in: query
          required: false
          description: |
            Use to filter by a specific agency (or multiple agencies).
            Comma-separated list of agency names.
          schema:
            type: array
            items:
              type: string
            example:
              - example_agency
          style: form
          explode: false

        - name: additional_fields
          in: query
          required: false
          description: |
            Comma-separated list of additional fields to include in the export.

            If not sent, a default set is used, including (but not limited to):
            store_reinstall, impressions, contributor3_match_type, custom_dimension,
            conversion_type, gp_click_time, match_type, mediation_network, oaid,
            deeplink_url, blocked_reason, blocked_sub_reason, gp_broadcast_referrer,
            gp_install_begin, campaign_type, custom_data, rejected_reason,
            device_download_time, keyword_match_type, contributor1_match_type,
            contributor2_match_type, device_model, monetization_network, segment,
            is_lat, gp_referrer, blocked_reason_value, store_product_page,
            device_category, app_type, rejected_reason_value, ad_unit, keyword_id,
            placement, network_account_id, install_app_store, amazon_aid, att,
            engagement_type, contributor1_engagement_type, contributor2_engagement_type,
            contributor3_engagement_type, gdpr_applies, ad_user_data_enabled,
            ad_personalization_enabled, total_candidates.
          schema:
            type: array
            items:
              type: string
            example:
              - store_reinstall
              - impressions
              - conversion_type
              - gp_click_time
          style: form
          explode: false

      responses:
        "200":
          description: Raw installs report in CSV format.
          content:
            text/csv:
              schema:
                type: string
                format: binary
        "401":
          description: Unauthorized – invalid or missing bearer token.
        "4XX":
          description: Client error – invalid parameters or other request issues.
        "5XX":
          description: Server error on AppsFlyer side.
